name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      run: |
        python manage.py migrate
      env:
        DATABASE_URL: sqlite:///db.sqlite3 # Use SQLite for CI tests
    - name: Run Tests
      run: |
        python manage.py test
      env:
        DATABASE_URL: sqlite:///db.sqlite3 # Use SQLite for CI tests
    - name: Run Linter (Ruff)
      run: |
        pip install ruff
        ruff check .
